CREATE TABLE USERS
(
    ID        INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME  VARCHAR(255),
    FIRSTNAME VARCHAR(255),
    LASTNAME  VARCHAR(255),
    EMAIL     VARCHAR(255),
    PASSWORD  VARCHAR(255)
);

CREATE TABLE MONTH
(
    ID         long PRIMARY KEY AUTO_INCREMENT,
    MONTH_CODE VARCHAR(255),
    YEAR       INT
);

CREATE TABLE INCOME
(
    ID          long PRIMARY KEY AUTO_INCREMENT,
    VALUE       INT,
    INCOME_NAME VARCHAR(255)
);

CREATE TABLE CONS_TABLE
(
    ID              long PRIMARY KEY AUTO_INCREMENT,
    CONS_LINE_ID    long,
    CONS_TABLE_NAME VARCHAR(255),
    MONTH_ID        long
);

ALTER TABLE CONS_TABLE
    ADD FOREIGN KEY (MONTH_ID) REFERENCES MONTH (ID);


CREATE TABLE CONS_LINE
(
    ID            LONG PRIMARY KEY AUTO_INCREMENT,
    PLANNED_SUM   INT,
    SUM           INT,
    FACT_SUM      INT,
    NAME          VARCHAR(255),
    CONS_TABLE_ID LONG
);

ALTER TABLE CONS_LINE
    ADD FOREIGN KEY (CONS_TABLE_ID) REFERENCES CONS_TABLE (ID);
